### PR TITLE
Use pactl only for PipeWire compatibility

### PR DESCRIPTION
**Pull request by Klok-e**
I recently moved to pipewire and this script stopped working, so I fixed it.

I didn't test this thoroughly on pulseaudio, so it needs some testing before it can be merged.

### CODE REVIEW

**Comment by pzmarzly** [comment]
Thanks a lot for the code. I'm positively surprised that PipeWire's PulseAudio compatibility layer is good enough to make the script work without many changes. I'll test the code a bit next week, if that's okay for you.

Out of curiosity, does everything work on PipeWire? Is it worthwhile to switch?

**Comment by LokiVKlokeNaAndoke** [comment]
Yeah, I'm OK with that.

Everything works so far, and it doesn't have problems I encountered on pulseaudio, like some sinks not having audio recorded by OBS, so I had to hack up an intermediate remap sink. Overall, I'm happy with the switch.

**Comment by LokiVKlokeNaAndoke** [comment]
@pzmarzly Any updates?

**Comment by siddhpant** [comment]
Please have a look at https://github.com/siddhpant/broo , I added PipeWire support along with other features.

**Comment by pzmarzly** [comment]
Closing in favor of #29 

I'll put https://github.com/siddhpant/broo in README as a more maintained alternative

**Pull request closed without merging**
